var GameSettings = {
    "embedded": false,
    "basePlatformUrl": "",
    "basePlatformExternalUrl": "",
    "baseAssetUrl": true,
    "developerMode": false,
    "isChromeApp": true,
    "isStandalone": true,
    "trackName": "track.txt",
    "fullscreenAvailable": true,
    "portal": "",
    "platform": "web",
    "drawFPS": 30,
    "defaultContainerID": "game-container",
    "width": 900,
    "height": 500,
    "fullscreen": false,
    "editorFullscreen": true,
    "drawSectorSize": 200,
    "physicsSectorSize": 100,
    "startVehicle": "BMX",
    "startTool": "straightline",
    "startPowerup": "goal",
    "defaultGravityX": 0,
    "defaultGravityY": 0.3,
    "cameraStartZoom": 0.5,
    "cameraZoomMin": 0.05,
    "cameraZoomMax": 4,
    "cameraSensitivity": 0.1,
    "cameraMovementVertical": true,
    "cameraMovementHorizontal": true,
    "lowQualityMode": false,
    "device": "desktop",
    "mobile": false,
    "controls": false,
    "startPaused": false,
    "waitForKeyPress": true,
    "waitAtCheckpoints": true,
    "trackCodeVersion": 1,
    "replayVersion": 1,
    "physicsLineColor": "#000",
    "sceneryLineColor": "#AAA",
    "foregroundLineColor": "AAA",
    "hatColor": "rgb(255,255,255)",
    "windspeed": 1,
    "propeller" : 1,
    "rotateFactor": 15,
    "scaleFactor": 1.25,
    "scaleLock": true,
    "accel": 1,
    "wind": 0,
    "gravity": 1,
    "mini" : 0.7,
    "add": true,
    "switchHotkeys": false,
    "snapNear": true,
    "snapDistance": 10,
    "visibleHitboxes": false,
    "textOffset": 100,
    "offsetPeteX": 0,
    "offsetPeteY": 0,
    "head": "cowboy",
    "freeFloppyPete": false,
    "customBrush": true,
    "lineTrim": false,
    "cameraSpeed": 3,
    "brushRotate": false,
    "brushScale": false,
    "brushRotateJitter": 0,
    "brushScaleJitter": 0,
    "objectRotate": 0,
    "objectScale": 1,
    "rotateSensitivity": 15,
    "scaleSensitivity": 0.1,
    "objectOffsetX": 0,
    "objectOffsetY": 0,
    "objectFlipX" : false,
    "objectFlipY" : false,
    "objectInvert" : false,
    "objectInvertFlat" : false,
    "object": true,
    "raceColors": ["rgba(57,185,117,1)", "rgba(0,152,189,1)", "rgba(151,95,162,1)", "rgba(253,85,91,1)", "rgba(245,126,64,1)", "rgba(247,212,62,1)", "rgba(170,221,114,1)", "rgba(72,217,207,1)", "rgba(0,124,212,1)", "rgba(226,108,216,1)"],
    "toolHandler": {
        "snap": false,
        "snapLocked": false,
        "cameraLocked": false,
        "grid": false,
        "gridSize": 10,
        "visibleGrid": true,
        "snapGrid": true,
        "gridMinorLineColor": "#EEE",
        "gridMajorLineColor": "#CCC",
        "lineType": "physics",
        "cameraMoveSpeed": 0.02,
        "rightClickMove": false,
        "copy": true,
        "isometricGrid": false,
        "isoWidth": 1
    },
    "vehiclePowerup": {
        "selected": "helicopter",
        "time": 10,
        "step": 1,
        "minTime": 5,
        "maxTime": 60
    },
    "eraser": {
        "radius": 29,
        "maxRadius": 200,
        "minRadius": 2,
        "radiusSizeSensitivity": 5,
        "types": {
            "scenery": true,
            "physics": true,
            "powerups": true
        }
    },
    "circle": {
        "segmentLength": 0.4,
        "maxSegmentLength": 1,
        "minSegmentLength": 0.1,
        "segmentLengthSensitivity": 0.1
    },
    "curve": {
        "segmentLength": 4,
        "maxSegmentLength": 10,
        "minSegmentLength": 1,
        "segmentLengthSensitivity": 1
    },
    "brush": {
        "breakLength": 0.2,
        "maxBreakLength": 5,
        "minBreakLength": 0.01,
        "breakLengthSensitivity": 0.1,
        "trailSpeed": 1,
        "maxTrailSpeed": 1,
        "minTrailSpeed": 0.01,
        "trailSpeedSensitivity": 0.1,
    },
    "select": {
        "types": {
            "scenery": true,
            "physics": true,
            "powerups": true
        }
    },
    "playHotkeys": {
        "up": [38],
        "down": [40],
        "left": [37],
        "right": [39],
        "pause": 32,
        "enter": 13,
        "backspace": 8,
        "z": 90,
        "x": 88,
        "zoom_increase": 187,
        "zoom_decrease": 189,
        "zoom_100": 48,
        "change_vehicle": 86
    },
    "editorHotkeys": {
        "up": 38,
        "down": 40,
        "left": 37,
        "right": 39,
        "z": 90,
        "y": 89,
        "x": 88,
        "snap": 17,
        "lineType": 9,
        "eraser": 69,
        "straightline": 81,
        "brush": 65,
        "curve": 87,
        "grid": 71,
        "camera": 67,
        "pause": 32,
        "change_vehicle": 86,
        "powerup": 80,
        "vehiclepowerup": 79,
        "opt1": 49,
        "opt2": 50,
        "opt3": 51,
        "opt4": 52,
        "opt5": 53,
        "opt6": 54,
        "opt7" : 55,
        "opt8" : 56,
        "enter": 13,
        "backspace": 8,
        "shift": 16,
        "ctrl": 17,
        "alt": 18,
        "zoom_increase": 187,
        "zoom_decrease": 189,
        "zoom_100": 48,
        "select" : 68,
        "circle" : 84,
        "invert" : 73,
        "rotate" : 82,
        "scale" : 83,
        "flip" : 70
    },
    "keysToRecord": ["up", "down", "left", "right", "enter", "backspace", "z"],
    "user": {
        "d_name": "Guest",
        "u_id": false,
        "cosmetics": {
            "head": {
                "id": "1",
                "title": "Classic Hat",
                "type": "1",
                "name": "classic",
                "cost": "0",
                "owner": true,
                "options": {
                    "back": "white"
                },
                "classname": "forwardcap",
                "equiped": false,
                "img": "",
                "show": true,
                "script": "",
                "limited": false
            }
        },
        "guest": true
    },
    "showHelpControls": false,
    "isCampaign": false,
    "track": false,
    "userTrackStats": false,
    "campaignData": false,
    "trackUploadCost": 0,
    "raceUids": false,
    "raceData": false,
    "soundsEnabled": false,
    "bestGhostEnabled": false,
    "requireTrackVerification": true
}